//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 02:54:07 PM EST 
//


package org.imsglobal.xsd.apip.apipv1p0.imsapip_qtiv1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The APIPAccessibility complexType is the top level container for all of the APIP information used to describe the accessibility features to be added to a QTI XML description of a QTI Item. This optional information consists of: companion materials, the inclusion orders to be used rendering the content in trems of the new accessibility information, and the set of accessibility information itself.
 *             
 * 
 * <p>Java class for APIPAccessibility.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="APIPAccessibility.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="companionMaterialsInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}CompanionMaterialsInfo.Type" minOccurs="0"/>
 *         &lt;element name="inclusionOrder" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}InclusionOrder.Type" minOccurs="0"/>
 *         &lt;element name="accessibilityInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}AccessibilityInfo.Type" minOccurs="0"/>
 *         &lt;group ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}grpStrict.any"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APIPAccessibility.Type", propOrder = {
    "companionMaterialsInfo",
    "inclusionOrder",
    "accessibilityInfo",
    "any"
})
public class APIPAccessibilityType {

    protected CompanionMaterialsInfoType companionMaterialsInfo;
    protected InclusionOrderType inclusionOrder;
    protected AccessibilityInfoType accessibilityInfo;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the companionMaterialsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CompanionMaterialsInfoType }
     *     
     */
    public CompanionMaterialsInfoType getCompanionMaterialsInfo() {
        return companionMaterialsInfo;
    }

    /**
     * Sets the value of the companionMaterialsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanionMaterialsInfoType }
     *     
     */
    public void setCompanionMaterialsInfo(CompanionMaterialsInfoType value) {
        this.companionMaterialsInfo = value;
    }

    /**
     * Gets the value of the inclusionOrder property.
     * 
     * @return
     *     possible object is
     *     {@link InclusionOrderType }
     *     
     */
    public InclusionOrderType getInclusionOrder() {
        return inclusionOrder;
    }

    /**
     * Sets the value of the inclusionOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link InclusionOrderType }
     *     
     */
    public void setInclusionOrder(InclusionOrderType value) {
        this.inclusionOrder = value;
    }

    /**
     * Gets the value of the accessibilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AccessibilityInfoType }
     *     
     */
    public AccessibilityInfoType getAccessibilityInfo() {
        return accessibilityInfo;
    }

    /**
     * Sets the value of the accessibilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessibilityInfoType }
     *     
     */
    public void setAccessibilityInfo(AccessibilityInfoType value) {
        this.accessibilityInfo = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
