//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 02:54:07 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.imsglobal.xsd.apip.apipv1p0.imsapip_qtiv1p0;
