//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 02:54:07 PM EST 
//


package org.imsglobal.xsd.apip.apipv1p0.imsapip_qtiv1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The RevealAlternativeRepresentation complexType is the container for the alternative representation that is to be rendered. Note that each alternative representation must be defined as its own access element.
 *             
 * 
 * <p>Java class for RevealAlternativeRepresentation.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RevealAlternativeRepresentation.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="audioFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}AudioFileInfo.Type" minOccurs="0"/>
 *         &lt;element name="videoFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}VideoFileInfo.Type" minOccurs="0"/>
 *         &lt;element name="graphicFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}ObjectFileInfo.Type" minOccurs="0"/>
 *         &lt;element name="textFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}ObjectFileInfo.Type" minOccurs="0"/>
 *         &lt;element name="textString" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}LabelledString.Type" minOccurs="0"/>
 *         &lt;element name="markupFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}ObjectFileInfo.Type" minOccurs="0"/>
 *         &lt;element name="markupFileEmbedded" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}MarkupFileEmbedded.Type" minOccurs="0"/>
 *         &lt;element name="executableFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}ObjectFileInfo.Type" minOccurs="0"/>
 *         &lt;group ref="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}grpStrict.any"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RevealAlternativeRepresentation.Type", propOrder = {
    "audioFileInfo",
    "videoFileInfo",
    "graphicFileInfo",
    "textFileInfo",
    "textString",
    "markupFileInfo",
    "markupFileEmbedded",
    "executableFileInfo",
    "any"
})
public class RevealAlternativeRepresentationType {

    protected AudioFileInfoType audioFileInfo;
    protected VideoFileInfoType videoFileInfo;
    protected ObjectFileInfoType graphicFileInfo;
    protected ObjectFileInfoType textFileInfo;
    protected LabelledStringType textString;
    protected ObjectFileInfoType markupFileInfo;
    protected MarkupFileEmbeddedType markupFileEmbedded;
    protected ObjectFileInfoType executableFileInfo;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the audioFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AudioFileInfoType }
     *     
     */
    public AudioFileInfoType getAudioFileInfo() {
        return audioFileInfo;
    }

    /**
     * Sets the value of the audioFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioFileInfoType }
     *     
     */
    public void setAudioFileInfo(AudioFileInfoType value) {
        this.audioFileInfo = value;
    }

    /**
     * Gets the value of the videoFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link VideoFileInfoType }
     *     
     */
    public VideoFileInfoType getVideoFileInfo() {
        return videoFileInfo;
    }

    /**
     * Sets the value of the videoFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoFileInfoType }
     *     
     */
    public void setVideoFileInfo(VideoFileInfoType value) {
        this.videoFileInfo = value;
    }

    /**
     * Gets the value of the graphicFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public ObjectFileInfoType getGraphicFileInfo() {
        return graphicFileInfo;
    }

    /**
     * Sets the value of the graphicFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public void setGraphicFileInfo(ObjectFileInfoType value) {
        this.graphicFileInfo = value;
    }

    /**
     * Gets the value of the textFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public ObjectFileInfoType getTextFileInfo() {
        return textFileInfo;
    }

    /**
     * Sets the value of the textFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public void setTextFileInfo(ObjectFileInfoType value) {
        this.textFileInfo = value;
    }

    /**
     * Gets the value of the textString property.
     * 
     * @return
     *     possible object is
     *     {@link LabelledStringType }
     *     
     */
    public LabelledStringType getTextString() {
        return textString;
    }

    /**
     * Sets the value of the textString property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelledStringType }
     *     
     */
    public void setTextString(LabelledStringType value) {
        this.textString = value;
    }

    /**
     * Gets the value of the markupFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public ObjectFileInfoType getMarkupFileInfo() {
        return markupFileInfo;
    }

    /**
     * Sets the value of the markupFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public void setMarkupFileInfo(ObjectFileInfoType value) {
        this.markupFileInfo = value;
    }

    /**
     * Gets the value of the markupFileEmbedded property.
     * 
     * @return
     *     possible object is
     *     {@link MarkupFileEmbeddedType }
     *     
     */
    public MarkupFileEmbeddedType getMarkupFileEmbedded() {
        return markupFileEmbedded;
    }

    /**
     * Sets the value of the markupFileEmbedded property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkupFileEmbeddedType }
     *     
     */
    public void setMarkupFileEmbedded(MarkupFileEmbeddedType value) {
        this.markupFileEmbedded = value;
    }

    /**
     * Gets the value of the executableFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public ObjectFileInfoType getExecutableFileInfo() {
        return executableFileInfo;
    }

    /**
     * Sets the value of the executableFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectFileInfoType }
     *     
     */
    public void setExecutableFileInfo(ObjectFileInfoType value) {
        this.executableFileInfo = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
