//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 02:54:07 PM EST 
//


package org.imsglobal.xsd.apip.apipv1p0.imsapip_qtiv1p0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The Spoken complexType is the container for the spoken accessibility content as an alternative to visual content.
 *             
 * 
 * <p>Java class for Spoken.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Spoken.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="audioFileInfo" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}AudioFileInfo.Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="spokenText" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}LabelledString.Type" minOccurs="0"/>
 *         &lt;element name="textToSpeechPronunciation" type="{http://www.imsglobal.org/xsd/apip/apipv1p0/imsapip_qtiv1p0}LabelledString.Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Spoken.Type", propOrder = {
    "audioFileInfo",
    "spokenText",
    "textToSpeechPronunciation"
})
public class SpokenType {

    protected List<AudioFileInfoType> audioFileInfo;
    protected LabelledStringType spokenText;
    protected LabelledStringType textToSpeechPronunciation;

    /**
     * Gets the value of the audioFileInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioFileInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioFileInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudioFileInfoType }
     * 
     * 
     */
    public List<AudioFileInfoType> getAudioFileInfo() {
        if (audioFileInfo == null) {
            audioFileInfo = new ArrayList<AudioFileInfoType>();
        }
        return this.audioFileInfo;
    }

    /**
     * Gets the value of the spokenText property.
     * 
     * @return
     *     possible object is
     *     {@link LabelledStringType }
     *     
     */
    public LabelledStringType getSpokenText() {
        return spokenText;
    }

    /**
     * Sets the value of the spokenText property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelledStringType }
     *     
     */
    public void setSpokenText(LabelledStringType value) {
        this.spokenText = value;
    }

    /**
     * Gets the value of the textToSpeechPronunciation property.
     * 
     * @return
     *     possible object is
     *     {@link LabelledStringType }
     *     
     */
    public LabelledStringType getTextToSpeechPronunciation() {
        return textToSpeechPronunciation;
    }

    /**
     * Sets the value of the textToSpeechPronunciation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelledStringType }
     *     
     */
    public void setTextToSpeechPronunciation(LabelledStringType value) {
        this.textToSpeechPronunciation = value;
    }

}
