//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 02:54:07 PM EST 
//


package org.imsglobal.xsd.apip.apipv1p0.imsapip_qtiv1p0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The StructuredMask complexType is the container for the settings to be aplied to a structured mask usage. The settings are the order of revelation for this object and whether or not it is to be applied to the answer fields of a question..
 *             
 * 
 * <p>Java class for StructuredMask.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StructuredMask.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="revealOrder" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="answerOption" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructuredMask.Type", propOrder = {
    "revealOrder",
    "answerOption"
})
public class StructuredMaskType {

    protected BigInteger revealOrder;
    @XmlElement(defaultValue = "true")
    protected Boolean answerOption;

    /**
     * Gets the value of the revealOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRevealOrder() {
        return revealOrder;
    }

    /**
     * Sets the value of the revealOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevealOrder(BigInteger value) {
        this.revealOrder = value;
    }

    /**
     * Gets the value of the answerOption property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnswerOption() {
        return answerOption;
    }

    /**
     * Sets the value of the answerOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnswerOption(Boolean value) {
        this.answerOption = value;
    }

}
