//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 01:37:27 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1", 
xmlns = { @XmlNs (namespaceURI = "http://www.imsglobal.org/xsd/imscp_v1p1", prefix = ""),
		@XmlNs(namespaceURI = "http://www.imsglobal.org/xsd/imsccv1p2/imscsmd_v1p0", prefix = "csm"),
		@XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi")
		
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.imsglobal.xsd.imscp_v1p1;

import javax.xml.bind.annotation.XmlNs;
