//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 04:32:48 PM EST 
//


package org.imsglobal.xsd.imsccv1p2.imscsmd_v1p0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.imsglobal.xsd.imsccv1p2.imscsmd_v1p0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CurriculumStandardsMetadataSet_QNAME = new QName("http://www.imsglobal.org/xsd/imsccv1p2/imscsmd_v1p0", "curriculumStandardsMetadataSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.imsglobal.xsd.imsccv1p2.imscsmd_v1p0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CurriculumStandardsMetadataSetType }
     * 
     */
    public CurriculumStandardsMetadataSetType createCurriculumStandardsMetadataSetType() {
        return new CurriculumStandardsMetadataSetType();
    }

    /**
     * Create an instance of {@link SetOfGUIDsType }
     * 
     */
    public SetOfGUIDsType createSetOfGUIDsType() {
        return new SetOfGUIDsType();
    }

    /**
     * Create an instance of {@link CurriculumStandardsMetadataType }
     * 
     */
    public CurriculumStandardsMetadataType createCurriculumStandardsMetadataType() {
        return new CurriculumStandardsMetadataType();
    }

    /**
     * Create an instance of {@link LabelledGUIDType }
     * 
     */
    public LabelledGUIDType createLabelledGUIDType() {
        return new LabelledGUIDType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurriculumStandardsMetadataSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imsglobal.org/xsd/imsccv1p2/imscsmd_v1p0", name = "curriculumStandardsMetadataSet")
    public JAXBElement<CurriculumStandardsMetadataSetType> createCurriculumStandardsMetadataSet(CurriculumStandardsMetadataSetType value) {
        return new JAXBElement<CurriculumStandardsMetadataSetType>(_CurriculumStandardsMetadataSet_QNAME, CurriculumStandardsMetadataSetType.class, null, value);
    }

}
