//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 02:54:07 PM EST 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.w3._2001.xinclude.IncludeType;


/**
 * 
 *                 The OutcomeProcessing complexType is the container for the outcome processing instructions. Outcome processing takes place each time the candidate submits the responses for an item (when in individual submission mode) or a group of items (when in simultaneous submission mode). It happens after any (item level) response processing triggered by the submission. The values of the test's outcome variables are always reset to their defaults prior to carrying out the instructions described by the outcomeRules. Because outcome processing happend each time the candidate submits responses the resulting values of the test-level outcomes may be used to activate test-level feedback during the test or to control the behaviour of subsequent parts through the use of preConditions and branchRules.
 *             
 * 
 * <p>Java class for OutcomeProcessing.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutcomeProcessing.Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}lookupOutcomeValue"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}outcomeProcessingFragment"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}setOutcomeValue"/>
 *           &lt;element ref="{http://www.w3.org/2001/XInclude}include"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}exitTest"/>
 *           &lt;element ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}outcomeCondition"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutcomeProcessing.Type", propOrder = {
    "lookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue"
})
public class OutcomeProcessingType {

    @XmlElements({
        @XmlElement(name = "lookupOutcomeValue", type = LookupOutcomeValueType.class),
        @XmlElement(name = "outcomeProcessingFragment", type = OutcomeProcessingFragmentType.class),
        @XmlElement(name = "setOutcomeValue", type = SetValueType.class),
        @XmlElement(name = "include", namespace = "http://www.w3.org/2001/XInclude", type = IncludeType.class),
        @XmlElement(name = "exitTest", type = EmptyPrimitiveTypeType.class),
        @XmlElement(name = "outcomeCondition", type = OutcomeConditionType.class)
    })
    protected List<Object> lookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue;

    /**
     * Gets the value of the lookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LookupOutcomeValueType }
     * {@link OutcomeProcessingFragmentType }
     * {@link SetValueType }
     * {@link IncludeType }
     * {@link EmptyPrimitiveTypeType }
     * {@link OutcomeConditionType }
     * 
     * 
     */
    public List<Object> getLookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue() {
        if (lookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue == null) {
            lookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue = new ArrayList<Object>();
        }
        return this.lookupOutcomeValueOrOutcomeProcessingFragmentOrSetOutcomeValue;
    }

}
