//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 02:54:07 PM EST 
//


package org.imsglobal.xsd.imsqti_v2p1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The TestEntryInteraction complexType is the container for information about a textEntry interaction. A textEntry interaction is an inlineInteraction that obtains a simple piece of text from the candidate. Like inlineChoiceInteraction, the delivery engine must allow the candidate to review their choice within the context of the surrounding text. The textEntryInteraction must be bound to a response variable with single cardinality only. The baseType must be one of string, integer or float. This complexType is intentionally empty.
 *             
 * 
 * <p>Java class for TextEntryInteraction.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextEntryInteraction.Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.imsglobal.org/xsd/imsqti_v2p1}EmptyPrimitiveType.Type">
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}placeholderText.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}label.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}xmllang.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}responseIdentifier.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}stringIdentifier.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}base.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}expectedLength.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}class.TextEntryInteraction.Attr"/>
 *       &lt;attGroup ref="{http://www.imsglobal.org/xsd/imsqti_v2p1}patternMask.TextEntryInteraction.Attr"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextEntryInteraction.Type")
public class TextEntryInteractionType
    extends EmptyPrimitiveTypeType
{

    @XmlAttribute(name = "placeholderText")
    protected String placeholderText;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "responseIdentifier", required = true)
    @XmlIDREF
    protected Object responseIdentifier;
    @XmlAttribute(name = "stringIdentifier")
    @XmlIDREF
    protected Object stringIdentifier;
    @XmlAttribute(name = "base2")
    protected Integer base2;
    @XmlAttribute(name = "expectedLength")
    protected Integer expectedLength;
    @XmlAttribute(name = "class")
    protected List<String> clazz;
    @XmlAttribute(name = "patternMask")
    protected String patternMask;

    /**
     * Gets the value of the placeholderText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceholderText() {
        return placeholderText;
    }

    /**
     * Sets the value of the placeholderText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceholderText(String value) {
        this.placeholderText = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the responseIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getResponseIdentifier() {
        return responseIdentifier;
    }

    /**
     * Sets the value of the responseIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setResponseIdentifier(Object value) {
        this.responseIdentifier = value;
    }

    /**
     * Gets the value of the stringIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStringIdentifier() {
        return stringIdentifier;
    }

    /**
     * Sets the value of the stringIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStringIdentifier(Object value) {
        this.stringIdentifier = value;
    }

    /**
     * Gets the value of the base2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getBase2() {
        if (base2 == null) {
            return  10;
        } else {
            return base2;
        }
    }

    /**
     * Sets the value of the base2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBase2(Integer value) {
        this.base2 = value;
    }

    /**
     * Gets the value of the expectedLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpectedLength() {
        return expectedLength;
    }

    /**
     * Sets the value of the expectedLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpectedLength(Integer value) {
        this.expectedLength = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getClazz() {
        if (clazz == null) {
            clazz = new ArrayList<String>();
        }
        return this.clazz;
    }

    /**
     * Gets the value of the patternMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatternMask() {
        return patternMask;
    }

    /**
     * Sets the value of the patternMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatternMask(String value) {
        this.patternMask = value;
    }

}
